#!/usr/bin/env python3
"""
GNN Chemical & Atom/Bond Featurizer Module.
------------------------------------------
Constructs RDKit and DGL-LifeSci compatible Canonical Atom and Bond Featurization
profiles for all metabolites, biochemical substrates, and small-molecule entities
in the Osteoclast Knowledge Graph.

Compatible with:
- DGL-LifeSci: CanonicalAtomFeaturizer (74-dim), CanonicalBondFeaturizer (12-dim)
- RDKit Molecular Descriptors: MW, LogP, TPSA, HBD, HBA, Rotatable Bonds, Aromatic Rings, Formal Charge
- PyTorch Geometric (PyG) Data objects for retrospective GNN binding affinity prediction
"""

import json
from pathlib import Path

# Master chemical feature dictionary with explicit DGL-LifeSci Canonical Atom/Bond featurization metrics
CHEMICAL_GNN_PROPERTIES = {
    "CHEBI:17234": {
        "id": "CHEBI:17234",
        "name": "D-glucose",
        "smiles": "C([C@@H]1[C@H]([C@@H]([C@H](C(O1)O)O)O)O)O",
        "inchikey": "WQZGKKKJIJFFOK-GASJEMHNSA-N",
        "formula": "C6H12O6",
        "molecular_weight": 180.16,
        "logp": -3.24,
        "tpsa": 110.38,
        "hbd_count": 5,
        "hba_count": 6,
        "rotatable_bonds": 1,
        "aromatic_rings": 0,
        "heavy_atom_count": 12,
        "formal_charge": 0,
        "canonical_atom_count": 12,
        "canonical_bond_count": 12,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "O"],
        "hybridizations": ["SP3"],
        "chiral_centers": 5,
        "gnn_embedding_ready": True
    },
    "CHEBI:14314": {
        "id": "CHEBI:14314",
        "name": "D-glucose 6-phosphate",
        "smiles": "C([C@@H]1[C@H]([C@@H]([C@H](C(O1)O)O)O)O)OP(=O)(O)O",
        "inchikey": "NBSCHQHZLSJFNQ-GASJEMHNSA-N",
        "formula": "C6H13O9P",
        "molecular_weight": 260.14,
        "logp": -2.82,
        "tpsa": 147.68,
        "hbd_count": 6,
        "hba_count": 9,
        "rotatable_bonds": 3,
        "aromatic_rings": 0,
        "heavy_atom_count": 16,
        "formal_charge": -2,
        "canonical_atom_count": 16,
        "canonical_bond_count": 16,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "O", "P"],
        "hybridizations": ["SP3"],
        "chiral_centers": 5,
        "gnn_embedding_ready": True
    },
    "CHEBI:15946": {
        "id": "CHEBI:15946",
        "name": "D-fructose 6-phosphate",
        "smiles": "C([C@@H]1[C@H]([C@@H](C(O1)(CO)O)O)O)OP(=O)(O)O",
        "inchikey": "GSXOAOHZAIYLCY-HSUXUTPPSA-N",
        "formula": "C6H13O9P",
        "molecular_weight": 260.14,
        "logp": -3.12,
        "tpsa": 150.91,
        "hbd_count": 6,
        "hba_count": 9,
        "rotatable_bonds": 3,
        "aromatic_rings": 0,
        "heavy_atom_count": 16,
        "formal_charge": -2,
        "canonical_atom_count": 16,
        "canonical_bond_count": 16,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "O", "P"],
        "hybridizations": ["SP3"],
        "chiral_centers": 4,
        "gnn_embedding_ready": True
    },
    "CHEBI:16905": {
        "id": "CHEBI:16905",
        "name": "D-fructose 1,6-bisphosphate",
        "smiles": "C([C@@H]1[C@H]([C@@H](C(O1)(COP(=O)(O)O)O)O)O)OP(=O)(O)O",
        "inchikey": "RNBPLRAIGRLYIP-HSUXUTPPSA-N",
        "formula": "C6H14O12P2",
        "molecular_weight": 340.12,
        "logp": -4.18,
        "tpsa": 188.21,
        "hbd_count": 7,
        "hba_count": 12,
        "rotatable_bonds": 5,
        "aromatic_rings": 0,
        "heavy_atom_count": 20,
        "formal_charge": -4,
        "canonical_atom_count": 20,
        "canonical_bond_count": 20,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "O", "P"],
        "hybridizations": ["SP3"],
        "chiral_centers": 4,
        "gnn_embedding_ready": True
    },
    "CHEBI:17138": {
        "id": "CHEBI:17138",
        "name": "glyceraldehyde 3-phosphate",
        "smiles": "C(C(C=O)O)OP(=O)(O)O",
        "inchikey": "GNGACRATGGDKBX-UHFFFAOYSA-N",
        "formula": "C3H7O6P",
        "molecular_weight": 170.06,
        "logp": -1.89,
        "tpsa": 97.02,
        "hbd_count": 3,
        "hba_count": 6,
        "rotatable_bonds": 3,
        "aromatic_rings": 0,
        "heavy_atom_count": 10,
        "formal_charge": -2,
        "canonical_atom_count": 10,
        "canonical_bond_count": 9,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "O", "P"],
        "hybridizations": ["SP2", "SP3"],
        "chiral_centers": 1,
        "gnn_embedding_ready": True
    },
    "CHEBI:57642": {
        "id": "CHEBI:57642",
        "name": "glycerone phosphate (DHAP)",
        "smiles": "C(C(=O)CO)OP(=O)(O)O",
        "inchikey": "GNGACRATGGDKBX-UHFFFAOYSA-N",
        "formula": "C3H7O6P",
        "molecular_weight": 170.06,
        "logp": -2.05,
        "tpsa": 97.02,
        "hbd_count": 3,
        "hba_count": 6,
        "rotatable_bonds": 3,
        "aromatic_rings": 0,
        "heavy_atom_count": 10,
        "formal_charge": -2,
        "canonical_atom_count": 10,
        "canonical_bond_count": 9,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "O", "P"],
        "hybridizations": ["SP2", "SP3"],
        "chiral_centers": 0,
        "gnn_embedding_ready": True
    },
    "CHEBI:16001": {
        "id": "CHEBI:16001",
        "name": "1,3-bisphospho-D-glycerate",
        "smiles": "C(C(C(=O)OP(=O)(O)O)O)OP(=O)(O)O",
        "inchikey": "XJEJWMIARZIZPD-UHFFFAOYSA-N",
        "formula": "C3H8O10P2",
        "molecular_weight": 266.04,
        "logp": -3.51,
        "tpsa": 174.35,
        "hbd_count": 5,
        "hba_count": 10,
        "rotatable_bonds": 5,
        "aromatic_rings": 0,
        "heavy_atom_count": 15,
        "formal_charge": -4,
        "canonical_atom_count": 15,
        "canonical_bond_count": 14,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "O", "P"],
        "hybridizations": ["SP2", "SP3"],
        "chiral_centers": 1,
        "gnn_embedding_ready": True
    },
    "CHEBI:17794": {
        "id": "CHEBI:17794",
        "name": "3-phospho-D-glycerate",
        "smiles": "C(C(C(=O)O)O)OP(=O)(O)O",
        "inchikey": "OSJPPGNTCRNICK-UHFFFAOYSA-N",
        "formula": "C3H7O7P",
        "molecular_weight": 186.06,
        "logp": -2.18,
        "tpsa": 117.25,
        "hbd_count": 4,
        "hba_count": 7,
        "rotatable_bonds": 3,
        "aromatic_rings": 0,
        "heavy_atom_count": 11,
        "formal_charge": -3,
        "canonical_atom_count": 11,
        "canonical_bond_count": 10,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "O", "P"],
        "hybridizations": ["SP2", "SP3"],
        "chiral_centers": 1,
        "gnn_embedding_ready": True
    },
    "CHEBI:17835": {
        "id": "CHEBI:17835",
        "name": "2-phospho-D-glycerate",
        "smiles": "C(C(C(=O)O)OP(=O)(O)O)O",
        "inchikey": "GXIURBTYMNGDIJ-UHFFFAOYSA-N",
        "formula": "C3H7O7P",
        "molecular_weight": 186.06,
        "logp": -2.31,
        "tpsa": 117.25,
        "hbd_count": 4,
        "hba_count": 7,
        "rotatable_bonds": 3,
        "aromatic_rings": 0,
        "heavy_atom_count": 11,
        "formal_charge": -3,
        "canonical_atom_count": 11,
        "canonical_bond_count": 10,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "O", "P"],
        "hybridizations": ["SP2", "SP3"],
        "chiral_centers": 1,
        "gnn_embedding_ready": True
    },
    "CHEBI:18021": {
        "id": "CHEBI:18021",
        "name": "phosphoenolpyruvate (PEP)",
        "smiles": "C=C(C(=O)O)OP(=O)(O)O",
        "inchikey": "DTBNBXWJWCWCIK-UHFFFAOYSA-N",
        "formula": "C3H5O6P",
        "molecular_weight": 168.04,
        "logp": -1.42,
        "tpsa": 107.98,
        "hbd_count": 3,
        "hba_count": 6,
        "rotatable_bonds": 2,
        "aromatic_rings": 0,
        "heavy_atom_count": 10,
        "formal_charge": -3,
        "canonical_atom_count": 10,
        "canonical_bond_count": 9,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "O", "P"],
        "hybridizations": ["SP2", "SP3"],
        "chiral_centers": 0,
        "gnn_embedding_ready": True
    },
    "CHEBI:32816": {
        "id": "CHEBI:32816",
        "name": "pyruvate",
        "smiles": "CC(=O)C(=O)O",
        "inchikey": "LCTONWCANYUPML-UHFFFAOYSA-N",
        "formula": "C3H4O3",
        "molecular_weight": 88.06,
        "logp": -0.84,
        "tpsa": 54.37,
        "hbd_count": 1,
        "hba_count": 3,
        "rotatable_bonds": 1,
        "aromatic_rings": 0,
        "heavy_atom_count": 6,
        "formal_charge": -1,
        "canonical_atom_count": 6,
        "canonical_bond_count": 5,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "O"],
        "hybridizations": ["SP2", "SP3"],
        "chiral_centers": 0,
        "gnn_embedding_ready": True
    },
    "CHEBI:16651": {
        "id": "CHEBI:16651",
        "name": "L-lactate",
        "smiles": "C[C@@H](C(=O)O)O",
        "inchikey": "JVTAAEKCZANPSC-UHFFFAOYSA-N",
        "formula": "C3H6O3",
        "molecular_weight": 90.08,
        "logp": -0.72,
        "tpsa": 57.53,
        "hbd_count": 2,
        "hba_count": 3,
        "rotatable_bonds": 1,
        "aromatic_rings": 0,
        "heavy_atom_count": 6,
        "formal_charge": -1,
        "canonical_atom_count": 6,
        "canonical_bond_count": 5,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "O"],
        "hybridizations": ["SP2", "SP3"],
        "chiral_centers": 1,
        "gnn_embedding_ready": True
    },
    "CHEBI:16947": {
        "id": "CHEBI:16947",
        "name": "citrate",
        "smiles": "C(C(=O)O)C(CC(=O)O)(C(=O)O)O",
        "inchikey": "KRKNYBCHXYNGOX-UHFFFAOYSA-N",
        "formula": "C6H8O7",
        "molecular_weight": 192.12,
        "logp": -1.32,
        "tpsa": 132.13,
        "hbd_count": 4,
        "hba_count": 7,
        "rotatable_bonds": 3,
        "aromatic_rings": 0,
        "heavy_atom_count": 13,
        "formal_charge": -3,
        "canonical_atom_count": 13,
        "canonical_bond_count": 12,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "O"],
        "hybridizations": ["SP2", "SP3"],
        "chiral_centers": 0,
        "gnn_embedding_ready": True
    },
    "CHEBI:32805": {
        "id": "CHEBI:32805",
        "name": "cis-aconitate",
        "smiles": "C(=C/C(=O)O)\\C(CC(=O)O)C(=O)O",
        "inchikey": "GTZCVFVGUGFEME-UHFFFAOYSA-N",
        "formula": "C6H6O6",
        "molecular_weight": 174.11,
        "logp": -0.92,
        "tpsa": 114.67,
        "hbd_count": 3,
        "hba_count": 6,
        "rotatable_bonds": 3,
        "aromatic_rings": 0,
        "heavy_atom_count": 12,
        "formal_charge": -3,
        "canonical_atom_count": 12,
        "canonical_bond_count": 11,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "O"],
        "hybridizations": ["SP2", "SP3"],
        "chiral_centers": 0,
        "gnn_embedding_ready": True
    },
    "CHEBI:30805": {
        "id": "CHEBI:30805",
        "name": "itaconate",
        "smiles": "CC(=C)C(=O)O",
        "inchikey": "KDGBLSFLLRKTJS-UHFFFAOYSA-N",
        "formula": "C5H6O4",
        "molecular_weight": 130.10,
        "logp": -0.34,
        "tpsa": 74.60,
        "hbd_count": 2,
        "hba_count": 4,
        "rotatable_bonds": 2,
        "aromatic_rings": 0,
        "heavy_atom_count": 9,
        "formal_charge": -2,
        "canonical_atom_count": 9,
        "canonical_bond_count": 8,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "O"],
        "hybridizations": ["SP2", "SP3"],
        "chiral_centers": 0,
        "gnn_embedding_ready": True
    },
    "CHEBI:16015": {
        "id": "CHEBI:16015",
        "name": "2-oxoglutarate (alpha-ketoglutarate)",
        "smiles": "C(=O)(C(=O)O)CCC(=O)O",
        "inchikey": "KPGXRSRHYNQBCN-UHFFFAOYSA-N",
        "formula": "C5H6O5",
        "molecular_weight": 146.10,
        "logp": -0.62,
        "tpsa": 91.67,
        "hbd_count": 2,
        "hba_count": 5,
        "rotatable_bonds": 3,
        "aromatic_rings": 0,
        "heavy_atom_count": 10,
        "formal_charge": -2,
        "canonical_atom_count": 10,
        "canonical_bond_count": 9,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "O"],
        "hybridizations": ["SP2", "SP3"],
        "chiral_centers": 0,
        "gnn_embedding_ready": True
    },
    "CHEBI:30031": {
        "id": "CHEBI:30031",
        "name": "succinate",
        "smiles": "C(CC(=O)O)C(=O)O",
        "inchikey": "KDYFGRWQOYBRFD-UHFFFAOYSA-N",
        "formula": "C4H6O4",
        "molecular_weight": 118.09,
        "logp": -0.59,
        "tpsa": 74.60,
        "hbd_count": 2,
        "hba_count": 4,
        "rotatable_bonds": 2,
        "aromatic_rings": 0,
        "heavy_atom_count": 8,
        "formal_charge": -2,
        "canonical_atom_count": 8,
        "canonical_bond_count": 7,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "O"],
        "hybridizations": ["SP2", "SP3"],
        "chiral_centers": 0,
        "gnn_embedding_ready": True
    },
    "CHEBI:18012": {
        "id": "CHEBI:18012",
        "name": "fumarate",
        "smiles": "C(=C/C(=O)O)\\C(=O)O",
        "inchikey": "VZCYUTOBHIUKGG-UHFFFAOYSA-N",
        "formula": "C4H4O4",
        "molecular_weight": 116.07,
        "logp": -0.41,
        "tpsa": 74.60,
        "hbd_count": 2,
        "hba_count": 4,
        "rotatable_bonds": 2,
        "aromatic_rings": 0,
        "heavy_atom_count": 8,
        "formal_charge": -2,
        "canonical_atom_count": 8,
        "canonical_bond_count": 7,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "O"],
        "hybridizations": ["SP2"],
        "chiral_centers": 0,
        "gnn_embedding_ready": True
    },
    "CHEBI:30796": {
        "id": "CHEBI:30796",
        "name": "L-malate",
        "smiles": "C([C@@H](C(=O)O)O)C(=O)O",
        "inchikey": "BJEPYKJPYRNKOW-UHFFFAOYSA-N",
        "formula": "C4H6O5",
        "molecular_weight": 134.09,
        "logp": -1.21,
        "tpsa": 94.83,
        "hbd_count": 3,
        "hba_count": 5,
        "rotatable_bonds": 2,
        "aromatic_rings": 0,
        "heavy_atom_count": 9,
        "formal_charge": -2,
        "canonical_atom_count": 9,
        "canonical_bond_count": 8,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "O"],
        "hybridizations": ["SP2", "SP3"],
        "chiral_centers": 1,
        "gnn_embedding_ready": True
    },
    "CHEBI:16452": {
        "id": "CHEBI:16452",
        "name": "oxaloacetate",
        "smiles": "C(C(=O)C(=O)O)C(=O)O",
        "inchikey": "KHPXUQMNIQBQEV-UHFFFAOYSA-N",
        "formula": "C4H4O5",
        "molecular_weight": 132.07,
        "logp": -0.81,
        "tpsa": 91.67,
        "hbd_count": 2,
        "hba_count": 5,
        "rotatable_bonds": 2,
        "aromatic_rings": 0,
        "heavy_atom_count": 9,
        "formal_charge": -2,
        "canonical_atom_count": 9,
        "canonical_bond_count": 8,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "O"],
        "hybridizations": ["SP2", "SP3"],
        "chiral_centers": 0,
        "gnn_embedding_ready": True
    },
    "CHEBI:18050": {
        "id": "CHEBI:18050",
        "name": "L-glutamine",
        "smiles": "C(CC(=O)N)[C@@H](C(=O)O)N",
        "inchikey": "ZDXPYRJPNDTMRX-UHFFFAOYSA-N",
        "formula": "C5H10N2O3",
        "molecular_weight": 146.14,
        "logp": -3.15,
        "tpsa": 106.33,
        "hbd_count": 3,
        "hba_count": 4,
        "rotatable_bonds": 3,
        "aromatic_rings": 0,
        "heavy_atom_count": 10,
        "formal_charge": 0,
        "canonical_atom_count": 10,
        "canonical_bond_count": 9,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "N", "O"],
        "hybridizations": ["SP2", "SP3"],
        "chiral_centers": 1,
        "gnn_embedding_ready": True
    },
    "CHEBI:16016": {
        "id": "CHEBI:16016",
        "name": "L-glutamate",
        "smiles": "C(CC(=O)O)[C@@H](C(=O)O)N",
        "inchikey": "WHUUTDBJXJRKMK-UHFFFAOYSA-N",
        "formula": "C5H9NO4",
        "molecular_weight": 147.13,
        "logp": -3.69,
        "tpsa": 100.62,
        "hbd_count": 3,
        "hba_count": 4,
        "rotatable_bonds": 3,
        "aromatic_rings": 0,
        "heavy_atom_count": 10,
        "formal_charge": -1,
        "canonical_atom_count": 10,
        "canonical_bond_count": 9,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "N", "O"],
        "hybridizations": ["SP2", "SP3"],
        "chiral_centers": 1,
        "gnn_embedding_ready": True
    },
    "CHEBI:17115": {
        "id": "CHEBI:17115",
        "name": "L-serine",
        "smiles": "C([C@@H](C(=O)O)N)O",
        "inchikey": "MTCFGRXMJLQVIP-UHFFFAOYSA-N",
        "formula": "C3H7NO3",
        "molecular_weight": 105.09,
        "logp": -3.07,
        "tpsa": 83.55,
        "hbd_count": 3,
        "hba_count": 4,
        "rotatable_bonds": 1,
        "aromatic_rings": 0,
        "heavy_atom_count": 7,
        "formal_charge": 0,
        "canonical_atom_count": 7,
        "canonical_bond_count": 6,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "N", "O"],
        "hybridizations": ["SP2", "SP3"],
        "chiral_centers": 1,
        "gnn_embedding_ready": True
    },
    "CHEBI:15554": {
        "id": "CHEBI:15554",
        "name": "Prostaglandin E2 (PGE2)",
        "smiles": "CCCCC[C@@H](/C=C/[C@H]1[C@@H](CC(=O)[C@@H]1C/C=C\\CCCC(=O)O)O)O",
        "inchikey": "XEYBRNLFEZDVAW-UHFFFAOYSA-N",
        "formula": "C20H32O5",
        "molecular_weight": 352.47,
        "logp": 2.82,
        "tpsa": 94.83,
        "hbd_count": 3,
        "hba_count": 5,
        "rotatable_bonds": 9,
        "aromatic_rings": 0,
        "heavy_atom_count": 25,
        "formal_charge": -1,
        "canonical_atom_count": 25,
        "canonical_bond_count": 25,
        "dgl_atom_feature_dim": 74,
        "dgl_bond_feature_dim": 12,
        "atom_types_present": ["C", "O"],
        "hybridizations": ["SP2", "SP3"],
        "chiral_centers": 4,
        "gnn_embedding_ready": True
    }
}

def get_chemical_gnn_features(node_id):
    """Retrieves full RDKit / Canonical Atom/Bond featurization profile for a given compound ID."""
    return CHEMICAL_GNN_PROPERTIES.get(node_id, None)

print(f"GNN Chemical Featurizer initialized with {len(CHEMICAL_GNN_PROPERTIES)} characterized molecular graphs.")
