"""Persist AI-assisted source-passage diagnostic judgments; not a biomedical gold set."""
import csv
from collections import Counter
from src.ingest.resolution_quality_pass import OUT,ROOT,read_jsonl,write_json

# Indexes refer to the frozen seed-20261002 simple random sample, not ranked selection.
NOTES={
0:'Chemical inhibition of c-Myc is not gene addition; molecular intervention needs clarification.',
1:'Cattle variant and protein complex require variant-specific identity.',
2:'Slit2 molecular form and intervention are not established by this conclusion.',
3:'Combination clinical treatment cannot be assigned to dasatinib alone.',
4:'General periodontal damage statement; not an osteoclast experiment.',
5:'RON is potentially resolvable, but genetic/pharmacological inhibition are combined and endpoint is broad.',
6:'Human correlation; serum cholesterol taxon was incorrectly assigned rat.',
7:'CRW acronym requires source definition and preparation identity.',
8:'Named compound needs registry mapping; combined pathway endpoint must stay composite.',
9:'Y27632 needs compound identity; large-cell generation is not identical to differentiation.',
10:'NP1 peptide/compound identity and assay reference need resolution.',
11:'Background MSC/exosome statement, not a new molecular experiment.',
12:'ADSC mineralization is an osteoblast-side endpoint; retain as separate biology.',
13:'Protein encoded by lncRNA and fragment antecedent need source review.',
14:'Explicit TRPM2 ablation supports qualified loss-of-function projection; retain alveolar endpoint.',
15:'Binding/thermal protection concerns TMED10 protein, not its gene; chemical identity also needed.',
16:'Human endothelial lipogenesis is outside immediate osteoclast mechanism scope.',
17:'Quote lacks named intervention; plant extract is a mixture.',
18:'Inflammatory mediator expression is not direct osteoclast outcome.',
19:'Osteoblast proliferation requires separate endpoint and context.',
20:'Extracellular vesicle preparation is not a single molecule.',
21:'Lacking PTPepsilon is valid depletion language missed by the lexical rule; endpoint context still needed.',
22:'Senolytic combination; implant loss is not a specific molecular outcome.',
23:'AMPK family and inhibitor intervention cannot become a single gene causal edge.',
24:'Background estrogen-deficiency statement.',
25:'Recruitment of SETD1A and TET2 dependence require protein/event representation.',
26:'RANKL-induced osteoclast differentiation is a qualified endpoint alias; preserve condition.',
27:'Anti-TNF treatment class is not a uniquely specified compound.',
28:'Review discussion of proto-oncogenes, not a new experiment.',
29:'Extract/chemical-class background statement.',
30:'Mitochondrial transfer and fragment antecedent need event-level evidence.',
31:'Combined PTHrP/RANKL exposure is not a genetic perturbation.',
32:'Bioceramic sealer is a material preparation, not a small molecule.',
33:'Dry immersion is a physiological intervention outside molecular target mapping.',
34:'Background cell-population effect, not a single molecule.',
35:'Exercise is a systemic intervention, not a molecular target edge.',
36:'Document-local IS/indoxyl sulfate alias and chemical identity could recover exposure evidence.',
37:'Review of peptide preparations, not a unique compound experiment.',
38:'Named drug is resolvable; cortical/trabecular endpoints need separate definitions.',
39:'Strontium hydroxyapatite material requires composition identity.',
40:'Quoted noun fragments do not establish a disease relation.',
41:'DHAP acronym requires article-specific definition; do not assume glycolytic metabolite.',
42:'SIN needs article-specific chemical definition.',
43:'ER dysfunction and SOCE are process nodes; do not guess a protein.',
44:'Fetal osteoblast cytokine response is a different cell context.',
45:'Named MPC inhibitor belongs in compound layer after registry resolution.',
46:'Osteogenesis response to DKK1 is a different endpoint and protein intervention.',
47:'Fragment does not name the exposure; CGD requires definition.',
48:'MDZ requires source-local definition; ROS is a chemical class.',
49:'SCFA class background; do not distribute the class claim to each compound.',
50:'Fragment does not identify SR1; phosphorylation is not automatically kinase activity.',
51:'Drug-loaded vesicles are composite interventions.',
52:'Explicit hypothesis; retain without observed-result promotion.',
53:'Fracture and pain endpoints in combination treatment are separate from osteoclast formation.',
54:'Background osteoblast metabolism statement.',
55:'CsCA preparation identity needs source definition.',
56:'Review of enzyme families and processes.',
57:'Incomplete quote and unknown Src molecular form require context retrieval.',
58:'ArA needs source-local chemical definition.',
59:'ADP-1 identity needed; source cell is osteoblast.',
60:'Cell-population association should not become protein binding.',
61:'Paper-local compound 3k requires chemical structure from full text.',
62:'Modal wording and direction unspecified; no signed effect established.',
63:'EV-mediated metabolite delivery requires donor/recipient and intervention separation.',
64:'MitoQ needs exact chemical form; preserve OTUD1-deficient background.',
65:'Paper-local SZQ-4 structure required.',
66:'Two noun fragments are insufficient evidence for a relation.',
67:'WSE extract identity and general bone endpoint remain unresolved.',
68:'AZD/AZD1390 abbreviation needs local definition; source typo must not be silently repaired.',
69:'No-effect observation should remain available as such, not become inhibition.',
70:'Full abstract mixes human tissue and calvarial model; human assignment is unsupported.',
71:'Correlation in a different scope, not causal osteoclast regulation.',
72:'Dasatinib identity is known; recruitment and formation are distinct outcomes.',
73:'Fragment lacks FAK manipulation and receptor form.',
74:'Bone-formation factors belong to a separate endpoint.',
75:'Multiple carotenoids named; chemical identities and individual treatment design needed.',
76:'ATP protonation and receptor/context need explicit mapping.',
77:'Named compound can enter separate exposure layer once identity is confirmed.',
78:'Dendritic-cell maturation with downstream bone outcome needs cell-to-cell mechanism.',
79:'OGT/OGA interventions at different stages must be separated; quote combines both.',
80:'TSG requires local chemical expansion.',
81:'Drug-class background statement.',
82:'Broad background axis statement; do not infer an individual gene mechanism.',
83:'Residue-specific G-protein/complex binding needs variant/event schema.',
84:'Tritherapy and adipogenesis are outside immediate osteoclast inference.',
85:'Phi chemical identity and RhoA protein form needed for binding claim.',
86:'Fragment omits Elmo1 manipulation; several targets are families.',
87:'Disconnected phrase spans do not establish pathway causal direction.',
88:'Background list of endocrine factors cannot become separate individual effects.',
89:'Cell-density protocol is an experimental condition, not a molecular entity.',
90:'Dry immersion abbreviation and systemic biomarker endpoint.',
91:'OPG exposure is incorrectly represented with osteoclasts as causal subject.',
92:'Expression correlation should remain unsigned; molecular form needs clarification.',
93:'Materials-class background statement.',
94:'Background stromal-cell RANKL mechanism; primary evidence needed.',
95:'BMSC osteogenesis belongs to separate outcome/context.',
96:'Review-level mitochondrial dysfunction association.',
97:'THF is ambiguous; do not assume tetrahydrofolate.',
98:'Specific stereochemical terrein exposure; registry identity and RNA endpoints needed.',
99:'Background metabolic requirement; no new experiment in quoted statement.',
100:'Background LYN mediation statement.',
101:'Definition of bone remodeling, not a perturbation result.',
102:'Background periodontitis statement.',
103:'Background RANKL essentiality statement.',
104:'Beta3 absence did not disrupt Pyk2 activation; preserve no-effect versus calcium dependence.',
105:'Review proposal, not observed result.',
106:'ICT/icaritin local alias recoverable; RNA/protein expression distinctions remain.',
107:'Lobelia extract is a mixture even when abbreviation is resolved.',
108:'Plasminogen-deficient mice are an organism/model, not a molecular subject.',
109:'Osteoblast effect; pronoun-only exposure requires preceding text.',
110:'Nonsignificant depression association is not a negative signed regulation.',
111:'Actin depolymerization is a distinct endpoint; no effect on sealing-zone formation.',
112:'Cilengitide identity is resolvable; FAK activation concerns protein, not gene.',
113:'Dasatinib/quercetin combination cannot be attributed to either constituent.',
114:'Combination treatment and systemic P1NP endpoint are not drug-specific osteoclast formation.',
115:'Named acacetin exposure is useful in chemical layer after registry mapping.',
116:'Osteogenesis/ferroptosis route does not by itself establish osteoclast mechanism.',
117:'Background inflammation association.',
118:'Glucocorticoid effect mediated by enzyme is not an HSD11B1 gene perturbation.',
119:'Quoted methods do not establish the summary result; cartilage context differs.',
}
GROUPS={
 'background_hypothesis_or_no_effect':[11,24,28,29,34,37,40,49,52,54,56,69,81,82,88,93,94,96,99,100,101,102,103,105,110,117],
 'different_context_or_endpoint':[4,6,12,16,18,19,33,35,44,46,53,66,71,74,78,84,95,109,116,119],
 'chemical_identity_or_exposure_layer':[7,8,9,10,15,27,32,36,38,39,41,42,45,48,55,58,59,61,64,65,67,68,72,75,76,77,80,85,97,98,106,107,112,113,114,115],
 'bounded_projection_or_process_mapping':[14,21,26,111],
}

def run():
    sample=read_jsonl(OUT/'random_audit_sample.jsonl')
    assert len(sample)==120 and set(NOTES)==set(range(120))
    category={i:group for group,indexes in GROUPS.items() for i in indexes}
    rows=[]
    for i,r in enumerate(sample):
        rows.append({'sample_index':i,'claim_id':r['claim_id'],'source_id':r['source_id'],'prior_reason':r['prior_reason'],'diagnostic_category':category.get(i,'intervention_form_species_or_passage_review'),'source_passage_note':NOTES[i],'reviewer':'AI-assisted passage inspection; not independent expert adjudication','quote':' | '.join(e['quote'] for e in r['claim']['evidence'])})
    with (OUT/'diagnostic_audit.csv').open('w',encoding='utf-8',newline='') as f:
        w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
    summary={'sample_design':'simple random sample without replacement of 120/4321 deferred claims; seed 20261002','categories':dict(Counter(r['diagnostic_category'] for r in rows)),'interpretation':'Diagnostic judgments of retrieved passages, not biomedical precision/recall. Categories describe the main follow-up; some claims have multiple defects. Sample used for development, not held-out evaluation.'}
    write_json(OUT/'audit_summary.json',summary);print(summary)

if __name__=='__main__': run()
